sudo: required
service:
 - docker
before_install:
  - docker build -t arunprabhut/travis:latest .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push arunprabhut/travis:latest
notifications:
 email:
   recipients:
     - refer.arun@gmail.com
   on_success: always
   on_failure: always
